-- ==============================================================================
-- CREATE GOVERNANCE MODULE TABLES (CORRECTED v3)
-- Fixed Foreign Key Types:
-- 1. client_id -> TEXT (matches clients.id)
-- 2. audit_id -> TEXT (matches audit_plans.id)
-- 3. related_audit_id -> TEXT (matches audit_plans.id)
-- ==============================================================================

-- 1. NCR (Non-Conformance Reports) Table
CREATE TABLE IF NOT EXISTS public.audit_ncrs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id TEXT REFERENCES public.clients(id) ON DELETE SET NULL,     -- Fixed: TEXT
    audit_id TEXT REFERENCES public.audit_plans(id) ON DELETE SET NULL,  -- Fixed: TEXT
    level TEXT NOT NULL,
    client_name TEXT,
    source TEXT,
    standard TEXT,
    clause TEXT,
    severity TEXT,
    description TEXT,
    raised_by TEXT,
    raised_date DATE,
    due_date DATE,
    status TEXT DEFAULT 'Open',
    correction TEXT,
    correction_date DATE,
    root_cause TEXT,
    corrective_action TEXT,
    capa_responsible TEXT,
    capa_implemented_date DATE,
    verification_method TEXT,
    verified_by TEXT,
    verified_date DATE,
    effectiveness TEXT,
    evidence JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Appeals Table
CREATE TABLE IF NOT EXISTS public.audit_appeals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id TEXT REFERENCES public.clients(id) ON DELETE SET NULL,     -- Fixed: TEXT
    client_name TEXT,
    type TEXT,
    subject TEXT,
    description TEXT,
    date_received DATE,
    due_date DATE,
    status TEXT DEFAULT 'Received',
    assigned_to TEXT,
    resolution TEXT,
    date_resolved DATE,
    history JSONB DEFAULT '[]'::jsonb,
    panel_records JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Complaints Table
CREATE TABLE IF NOT EXISTS public.audit_complaints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT,
    client_name TEXT,
    related_audit_id TEXT REFERENCES public.audit_plans(id) ON DELETE SET NULL, -- Fixed: TEXT
    type TEXT,
    severity TEXT,
    auditors_involved JSONB DEFAULT '[]'::jsonb,
    subject TEXT,
    description TEXT,
    date_received DATE,
    due_date DATE,
    status TEXT DEFAULT 'Received',
    investigator TEXT,
    findings TEXT,
    corrective_action TEXT,
    resolution TEXT,
    date_resolved DATE,
    history JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Impartiality Members Table
CREATE TABLE IF NOT EXISTS public.audit_impartiality_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    organization TEXT,
    role TEXT,
    expertise TEXT,
    appointed_date DATE,
    term_end DATE,
    status TEXT DEFAULT 'Active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Impartiality Threats Table
CREATE TABLE IF NOT EXISTS public.audit_impartiality_threats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE,
    type TEXT,
    description TEXT,
    client TEXT,
    safeguard TEXT,
    identified_by TEXT,
    status TEXT DEFAULT 'Open',
    reviewed_by_committee BOOLEAN DEFAULT FALSE,
    committee_decision TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Impartiality Meetings Table
CREATE TABLE IF NOT EXISTS public.audit_impartiality_meetings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE,
    attendees JSONB DEFAULT '[]'::jsonb,
    threats_reviewed JSONB DEFAULT '[]'::jsonb,
    decisions JSONB DEFAULT '[]'::jsonb,
    next_meeting_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Management Reviews Table
CREATE TABLE IF NOT EXISTS public.audit_management_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE,
    reviewed_by TEXT,
    attendees JSONB DEFAULT '[]'::jsonb,
    inputs JSONB DEFAULT '{}'::jsonb,
    outputs JSONB DEFAULT '{}'::jsonb,
    action_items JSONB DEFAULT '[]'::jsonb,
    next_review_date DATE,
    minutes_approved_by TEXT,
    minutes_approved_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. ENABLE RLS
ALTER TABLE public.audit_ncrs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_appeals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_complaints ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_impartiality_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_impartiality_threats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_impartiality_meetings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_management_reviews ENABLE ROW LEVEL SECURITY;

-- 9. CREATE RLS POLICIES (Authenticated Users Full Access)

-- NCRs
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.audit_ncrs;
CREATE POLICY "Enable read access for authenticated users" ON public.audit_ncrs FOR SELECT USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.audit_ncrs;
CREATE POLICY "Enable insert for authenticated users" ON public.audit_ncrs FOR INSERT WITH CHECK (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable update for authenticated users" ON public.audit_ncrs;
CREATE POLICY "Enable update for authenticated users" ON public.audit_ncrs FOR UPDATE USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable delete for authenticated users" ON public.audit_ncrs;
CREATE POLICY "Enable delete for authenticated users" ON public.audit_ncrs FOR DELETE USING (auth.role() = 'authenticated');

-- Appeals
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.audit_appeals;
CREATE POLICY "Enable read access for authenticated users" ON public.audit_appeals FOR SELECT USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.audit_appeals;
CREATE POLICY "Enable insert for authenticated users" ON public.audit_appeals FOR INSERT WITH CHECK (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable update for authenticated users" ON public.audit_appeals;
CREATE POLICY "Enable update for authenticated users" ON public.audit_appeals FOR UPDATE USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable delete for authenticated users" ON public.audit_appeals;
CREATE POLICY "Enable delete for authenticated users" ON public.audit_appeals FOR DELETE USING (auth.role() = 'authenticated');

-- Complaints
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.audit_complaints;
CREATE POLICY "Enable read access for authenticated users" ON public.audit_complaints FOR SELECT USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.audit_complaints;
CREATE POLICY "Enable insert for authenticated users" ON public.audit_complaints FOR INSERT WITH CHECK (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable update for authenticated users" ON public.audit_complaints;
CREATE POLICY "Enable update for authenticated users" ON public.audit_complaints FOR UPDATE USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable delete for authenticated users" ON public.audit_complaints;
CREATE POLICY "Enable delete for authenticated users" ON public.audit_complaints FOR DELETE USING (auth.role() = 'authenticated');

-- Impartiality Members
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.audit_impartiality_members;
CREATE POLICY "Enable read access for authenticated users" ON public.audit_impartiality_members FOR SELECT USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.audit_impartiality_members;
CREATE POLICY "Enable insert for authenticated users" ON public.audit_impartiality_members FOR INSERT WITH CHECK (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable update for authenticated users" ON public.audit_impartiality_members;
CREATE POLICY "Enable update for authenticated users" ON public.audit_impartiality_members FOR UPDATE USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable delete for authenticated users" ON public.audit_impartiality_members;
CREATE POLICY "Enable delete for authenticated users" ON public.audit_impartiality_members FOR DELETE USING (auth.role() = 'authenticated');

-- Impartiality Threats
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.audit_impartiality_threats;
CREATE POLICY "Enable read access for authenticated users" ON public.audit_impartiality_threats FOR SELECT USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.audit_impartiality_threats;
CREATE POLICY "Enable insert for authenticated users" ON public.audit_impartiality_threats FOR INSERT WITH CHECK (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable update for authenticated users" ON public.audit_impartiality_threats;
CREATE POLICY "Enable update for authenticated users" ON public.audit_impartiality_threats FOR UPDATE USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable delete for authenticated users" ON public.audit_impartiality_threats;
CREATE POLICY "Enable delete for authenticated users" ON public.audit_impartiality_threats FOR DELETE USING (auth.role() = 'authenticated');

-- Impartiality Meetings
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.audit_impartiality_meetings;
CREATE POLICY "Enable read access for authenticated users" ON public.audit_impartiality_meetings FOR SELECT USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.audit_impartiality_meetings;
CREATE POLICY "Enable insert for authenticated users" ON public.audit_impartiality_meetings FOR INSERT WITH CHECK (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable update for authenticated users" ON public.audit_impartiality_meetings;
CREATE POLICY "Enable update for authenticated users" ON public.audit_impartiality_meetings FOR UPDATE USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable delete for authenticated users" ON public.audit_impartiality_meetings;
CREATE POLICY "Enable delete for authenticated users" ON public.audit_impartiality_meetings FOR DELETE USING (auth.role() = 'authenticated');

-- Management Reviews
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.audit_management_reviews;
CREATE POLICY "Enable read access for authenticated users" ON public.audit_management_reviews FOR SELECT USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.audit_management_reviews;
CREATE POLICY "Enable insert for authenticated users" ON public.audit_management_reviews FOR INSERT WITH CHECK (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable update for authenticated users" ON public.audit_management_reviews;
CREATE POLICY "Enable update for authenticated users" ON public.audit_management_reviews FOR UPDATE USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable delete for authenticated users" ON public.audit_management_reviews;
CREATE POLICY "Enable delete for authenticated users" ON public.audit_management_reviews FOR DELETE USING (auth.role() = 'authenticated');

-- Verification
DO $$
BEGIN
    RAISE NOTICE 'Governance tables updated (Foreign Keys Fixed to TEXT: client_id, audit_id, related_audit_id) and RLS enabled.';
END $$;
