-- ==========================================
-- AUDITCB360 - FINAL DATABASE SCHEMA
-- Version: 2.0 (Production Ready)
-- ==========================================

-- 1. EXTENSIONS
create extension if not exists "uuid-ossp";

-- 2. ENUMS
create type app_role as enum ('Lead Auditor', 'Auditor', 'Technical Expert', 'Certification Manager', 'Admin');
create type audit_status as enum ('Draft', 'Scheduled', 'In Progress', 'Field Work Complete', 'Pending Review', 'Approved', 'Completed', 'Finalized');
create type user_status as enum ('Active', 'Pending', 'Inactive');

-- 3. PROFILES (Users)
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text unique not null,
  full_name text,
  role app_role default 'Auditor',
  status user_status default 'Pending',
  avatar_url text,
  qualification_standards text[], -- ['ISO 9001', 'ISO 14001']
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. CLIENTS
create table public.clients (
  id bigint generated by default as identity primary key,
  name text not null,
  industry text,
  standard text, -- e.g. "ISO 9001:2015"
  status text default 'Active',
  employees int default 0,
  shifts text default 'No',
  sites jsonb default '[]'::jsonb, -- Array of site objects
  contacts jsonb default '[]'::jsonb, -- Array of contact objects
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- 5. AUDIT PLANS
create table public.audit_plans (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id),
  client_name text, -- De-normalized for easier display
  standard text,
  type text, -- 'Stage 1', 'Stage 2', 'Surveillance', 'Recertification'
  start_date date,
  end_date date,
  man_days numeric(5,1),
  status audit_status default 'Draft',
  lead_auditor_id uuid references public.profiles(id),
  team_ids uuid[], -- Array of auditor IDs
  agenda jsonb default '[]'::jsonb,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- 6. AUDIT REPORTS
create table public.audit_reports (
  id bigint generated by default as identity primary key,
  plan_id bigint references public.audit_plans(id),
  client_name text,
  audit_date date,
  status text default 'Draft', -- 'Draft', 'Finalized'
  executive_summary text,
  conclusion text,
  recommendation text,
  generated_pdf_url text,
  checklist_progress jsonb default '[]'::jsonb, -- Granular checklist responses
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- 7. AUDIT FINDINGS (NCRs)
create table public.audit_findings (
  id uuid default uuid_generate_v4() primary key,
  report_id bigint references public.audit_reports(id),
  type text check (type in ('Major', 'Minor', 'OFI')),
  clause text,
  description text,
  evidence text,
  status text default 'Open', -- 'Open', 'Closed'
  created_at timestamp with time zone default now()
);

-- 8. AUDIT LOG (Audit Trail)
create table public.audit_log (
  id uuid default uuid_generate_v4() primary key,
  timestamp timestamp with time zone default now(),
  action text not null, -- 'LOGIN', 'CREATE_CLIENT', 'APPROVE_REPORT'
  entity text, -- 'Client', 'Report'
  entity_id text,
  user_id uuid references public.profiles(id),
  user_email text,
  user_role text,
  details jsonb -- Changed fields, metadata
);

-- 9. NOTIFICATIONS
create table public.notifications (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.profiles(id),
  message text not null,
  type text default 'info', -- 'info', 'success', 'warning', 'error'
  read boolean default false,
  created_at timestamp with time zone default now()
);

-- 10. SECURITY POLICIES (RLS)
alter table public.profiles enable row level security;
alter table public.clients enable row level security;
alter table public.audit_plans enable row level security;
alter table public.audit_reports enable row level security;
alter table public.audit_findings enable row level security;
alter table public.audit_log enable row level security;
alter table public.notifications enable row level security;

-- Profiles: View all (for team selection), Update own
create policy "Public Usage" on public.profiles for select using (true);
create policy "Self Update" on public.profiles for update using (auth.uid() = id);

-- Clients/Plans/Reports: 
-- In a real app, complex filtering based on assignments would go here.
-- For this setup, we allow Authenticated users to view all (Role Access Control handled in App Logic)
create policy "Authenticated View All" on public.clients for select to authenticated using (true);
create policy "Authenticated Modify" on public.clients for all to authenticated using (true); -- Restricted by App Logic

create policy "Authenticated View Plans" on public.audit_plans for select to authenticated using (true);
create policy "Authenticated Modify Plans" on public.audit_plans for all to authenticated using (true);

create policy "Authenticated View Reports" on public.audit_reports for select to authenticated using (true);
create policy "Authenticated Modify Reports" on public.audit_reports for all to authenticated using (true);

-- Functions
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, role, status)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', 'Auditor', 'Pending');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

