-- DISABLE RLS COMPLETELY (NUCLEAR OPTION)
ALTER TABLE clients DISABLE ROW LEVEL SECURITY;
ALTER TABLE auditors DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_plans DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE checklists DISABLE ROW LEVEL SECURITY;
ALTER TABLE settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE certification_decisions DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;

SELECT 'RLS disabled on all tables!' as status;
