-- ==============================================================================
-- FIX AND SETUP GOVERNANCE MODULE (CONSOLIDATED)
-- ==============================================================================
-- This script performs two key actions:
-- 1. UPDATES base tables (clients, audit_plans) to use TEXT for IDs.
--    Reason: The app uses Date.now() (numbers) or Strings, but previous schema used BIGINT/UUID.
--    TEXT is the most flexible type to prevent "foreign key type mismatch" errors.
-- 2. CREATES the Governance tables (NCRs, Appeals, etc.) with correct foreign keys.
-- ==============================================================================

-- PART 1: FIX BASE TABLE ID TYPES
-- ==============================================================================

DO $$ 
BEGIN
    -- 1. Fix Clients ID to TEXT
    BEGIN
        ALTER TABLE public.clients ALTER COLUMN id TYPE TEXT;
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'Skipping clients.id alter (likely already TEXT or has deps)';
    END;

    -- 2. Fix Audit Plans ID to TEXT
    BEGIN
        ALTER TABLE public.audit_plans ALTER COLUMN id TYPE TEXT;
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'Skipping audit_plans.id alter';
    END;

    -- 3. Fix Audit Reports ID to TEXT (for completeness)
    BEGIN
        ALTER TABLE public.audit_reports ALTER COLUMN id TYPE TEXT;
    EXCEPTION WHEN OTHERS THEN
        RAISE NOTICE 'Skipping audit_reports.id alter';
    END;
END $$;

-- PART 2: CREATE GOVERNANCE TABLES
-- ==============================================================================

-- 1. NCR (Non-Conformance Reports) Table
CREATE TABLE IF NOT EXISTS public.audit_ncrs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id TEXT REFERENCES public.clients(id) ON DELETE SET NULL,     -- Matches clients.id (TEXT)
    audit_id TEXT REFERENCES public.audit_plans(id) ON DELETE SET NULL,  -- Matches audit_plans.id (TEXT)
    level TEXT NOT NULL,
    client_name TEXT,
    source TEXT,
    standard TEXT,
    clause TEXT,
    severity TEXT,
    description TEXT,
    raised_by TEXT,
    raised_date DATE,
    due_date DATE,
    status TEXT DEFAULT 'Open',
    correction TEXT,
    correction_date DATE,
    root_cause TEXT,
    corrective_action TEXT,
    capa_responsible TEXT,
    capa_implemented_date DATE,
    verification_method TEXT,
    verified_by TEXT,
    verified_date DATE,
    effectiveness TEXT,
    evidence JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Appeals Table
CREATE TABLE IF NOT EXISTS public.audit_appeals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id TEXT REFERENCES public.clients(id) ON DELETE SET NULL,     -- Matches clients.id (TEXT)
    client_name TEXT,
    type TEXT,
    subject TEXT,
    description TEXT,
    date_received DATE,
    due_date DATE,
    status TEXT DEFAULT 'Received',
    assigned_to TEXT,
    resolution TEXT,
    date_resolved DATE,
    history JSONB DEFAULT '[]'::jsonb,
    panel_records JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Complaints Table
CREATE TABLE IF NOT EXISTS public.audit_complaints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT,
    client_name TEXT,
    related_audit_id TEXT REFERENCES public.audit_plans(id) ON DELETE SET NULL, -- Matches audit_plans.id (TEXT)
    type TEXT,
    severity TEXT,
    auditors_involved JSONB DEFAULT '[]'::jsonb,
    subject TEXT,
    description TEXT,
    date_received DATE,
    due_date DATE,
    status TEXT DEFAULT 'Received',
    investigator TEXT,
    findings TEXT,
    corrective_action TEXT,
    resolution TEXT,
    date_resolved DATE,
    history JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Impartiality Members Table
CREATE TABLE IF NOT EXISTS public.audit_impartiality_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    organization TEXT,
    role TEXT,
    expertise TEXT,
    appointed_date DATE,
    term_end DATE,
    status TEXT DEFAULT 'Active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Impartiality Threats Table
CREATE TABLE IF NOT EXISTS public.audit_impartiality_threats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE,
    type TEXT,
    description TEXT,
    client TEXT,
    safeguard TEXT,
    identified_by TEXT,
    status TEXT DEFAULT 'Open',
    reviewed_by_committee BOOLEAN DEFAULT FALSE,
    committee_decision TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Impartiality Meetings Table
CREATE TABLE IF NOT EXISTS public.audit_impartiality_meetings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE,
    attendees JSONB DEFAULT '[]'::jsonb,
    threats_reviewed JSONB DEFAULT '[]'::jsonb,
    decisions JSONB DEFAULT '[]'::jsonb,
    next_meeting_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Management Reviews Table
CREATE TABLE IF NOT EXISTS public.audit_management_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE,
    reviewed_by TEXT,
    attendees JSONB DEFAULT '[]'::jsonb,
    inputs JSONB DEFAULT '{}'::jsonb,
    outputs JSONB DEFAULT '{}'::jsonb,
    action_items JSONB DEFAULT '[]'::jsonb,
    next_review_date DATE,
    minutes_approved_by TEXT,
    minutes_approved_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- PART 3: ENABLE RLS AND POLICIES
-- ==============================================================================

-- ENABLE RLS
ALTER TABLE public.audit_ncrs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_appeals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_complaints ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_impartiality_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_impartiality_threats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_impartiality_meetings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_management_reviews ENABLE ROW LEVEL SECURITY;

-- CREATE RLS POLICIES (Full Access for Authenticated Users)

-- Helper macro for policy creation not available in raw SQL, so we expand them:

-- NCRs
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.audit_ncrs;
CREATE POLICY "Enable read access for authenticated users" ON public.audit_ncrs FOR SELECT USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.audit_ncrs;
CREATE POLICY "Enable insert for authenticated users" ON public.audit_ncrs FOR INSERT WITH CHECK (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable update for authenticated users" ON public.audit_ncrs;
CREATE POLICY "Enable update for authenticated users" ON public.audit_ncrs FOR UPDATE USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable delete for authenticated users" ON public.audit_ncrs;
CREATE POLICY "Enable delete for authenticated users" ON public.audit_ncrs FOR DELETE USING (auth.role() = 'authenticated');

-- Appeals
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.audit_appeals;
CREATE POLICY "Enable read access for authenticated users" ON public.audit_appeals FOR SELECT USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.audit_appeals;
CREATE POLICY "Enable insert for authenticated users" ON public.audit_appeals FOR INSERT WITH CHECK (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable update for authenticated users" ON public.audit_appeals;
CREATE POLICY "Enable update for authenticated users" ON public.audit_appeals FOR UPDATE USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable delete for authenticated users" ON public.audit_appeals;
CREATE POLICY "Enable delete for authenticated users" ON public.audit_appeals FOR DELETE USING (auth.role() = 'authenticated');

-- Complaints
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.audit_complaints;
CREATE POLICY "Enable read access for authenticated users" ON public.audit_complaints FOR SELECT USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.audit_complaints;
CREATE POLICY "Enable insert for authenticated users" ON public.audit_complaints FOR INSERT WITH CHECK (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable update for authenticated users" ON public.audit_complaints;
CREATE POLICY "Enable update for authenticated users" ON public.audit_complaints FOR UPDATE USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable delete for authenticated users" ON public.audit_complaints;
CREATE POLICY "Enable delete for authenticated users" ON public.audit_complaints FOR DELETE USING (auth.role() = 'authenticated');

-- Impartiality Members
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.audit_impartiality_members;
CREATE POLICY "Enable read access for authenticated users" ON public.audit_impartiality_members FOR SELECT USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.audit_impartiality_members;
CREATE POLICY "Enable insert for authenticated users" ON public.audit_impartiality_members FOR INSERT WITH CHECK (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable update for authenticated users" ON public.audit_impartiality_members;
CREATE POLICY "Enable update for authenticated users" ON public.audit_impartiality_members FOR UPDATE USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable delete for authenticated users" ON public.audit_impartiality_members;
CREATE POLICY "Enable delete for authenticated users" ON public.audit_impartiality_members FOR DELETE USING (auth.role() = 'authenticated');

-- Impartiality Threats
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.audit_impartiality_threats;
CREATE POLICY "Enable read access for authenticated users" ON public.audit_impartiality_threats FOR SELECT USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.audit_impartiality_threats;
CREATE POLICY "Enable insert for authenticated users" ON public.audit_impartiality_threats FOR INSERT WITH CHECK (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable update for authenticated users" ON public.audit_impartiality_threats;
CREATE POLICY "Enable update for authenticated users" ON public.audit_impartiality_threats FOR UPDATE USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable delete for authenticated users" ON public.audit_impartiality_threats;
CREATE POLICY "Enable delete for authenticated users" ON public.audit_impartiality_threats FOR DELETE USING (auth.role() = 'authenticated');

-- Impartiality Meetings
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.audit_impartiality_meetings;
CREATE POLICY "Enable read access for authenticated users" ON public.audit_impartiality_meetings FOR SELECT USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.audit_impartiality_meetings;
CREATE POLICY "Enable insert for authenticated users" ON public.audit_impartiality_meetings FOR INSERT WITH CHECK (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable update for authenticated users" ON public.audit_impartiality_meetings;
CREATE POLICY "Enable update for authenticated users" ON public.audit_impartiality_meetings FOR UPDATE USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable delete for authenticated users" ON public.audit_impartiality_meetings;
CREATE POLICY "Enable delete for authenticated users" ON public.audit_impartiality_meetings FOR DELETE USING (auth.role() = 'authenticated');

-- Management Reviews
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.audit_management_reviews;
CREATE POLICY "Enable read access for authenticated users" ON public.audit_management_reviews FOR SELECT USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.audit_management_reviews;
CREATE POLICY "Enable insert for authenticated users" ON public.audit_management_reviews FOR INSERT WITH CHECK (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable update for authenticated users" ON public.audit_management_reviews;
CREATE POLICY "Enable update for authenticated users" ON public.audit_management_reviews FOR UPDATE USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Enable delete for authenticated users" ON public.audit_management_reviews;
CREATE POLICY "Enable delete for authenticated users" ON public.audit_management_reviews FOR DELETE USING (auth.role() = 'authenticated');

-- Verification Output
DO $$
BEGIN
    RAISE NOTICE 'SUCCESS: Base tables (clients, audit_plans) IDs confirmed as TEXT, and Governance tables created with correct links.';
END $$;
