#!/usr/bin/env python3
"""
Compare the substantive text of two PDFs (before / after), ignoring the things
that change on every print: browser timestamps, the browser's document title,
"about:blank", page counters and the generation stamp. Answers one question:
did anything the reader cares about change, or only the metadata?

  python tools/compare_pdfs.py before.pdf after.pdf [--claims claims.json] [--out report.md]

Prints/Writes: page counts, how much substantive text changed, and (with
--claims) a before/after table for each named defect. Exit code 0 always; the
report is evidence, not a gate.
"""
import argparse
import difflib
import json
import re
from pathlib import Path

import fitz

NOISE = [
    re.compile(r"^\d{1,2}/\d{1,2}/\d{2,4},\s+\d{1,2}:\d{2}\s?(AM|PM)$", re.I),   # browser timestamp
    re.compile(r"^about:blank$", re.I),
    re.compile(r"^\d{1,3}/\d{1,3}$"),                                              # browser page counter
    re.compile(r"^Generated by .* Page \d+ of \d+$", re.I),
    re.compile(r"^Page \d+ of \d+$", re.I),
]


def substantive_lines(pdf: Path, drop_titles=()):
    doc = fitz.open(pdf)
    lines = []
    for page in doc:
        for raw in page.get_text().splitlines():
            s = re.sub(r"\s+", " ", raw).strip()
            if not s or any(rx.match(s) for rx in NOISE):
                continue
            if any(s.startswith(t) for t in drop_titles):
                continue
            lines.append(s)
    return doc.page_count, lines


def raw_text(pdf: Path):
    doc = fitz.open(pdf)
    return re.sub(r"\s+", " ", " ".join(page.get_text() for page in doc))


def words(lines):
    return re.findall(r"[A-Za-z0-9&.\-/:]+", " ".join(lines).lower())


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("before")
    ap.add_argument("after")
    ap.add_argument("--claims", default=None, help="JSON list of {label, before_contains, after_contains, before_absent, after_absent}")
    ap.add_argument("--out", default=None)
    a = ap.parse_args()

    bp, bl = substantive_lines(Path(a.before), drop_titles=("Audit Plan - ", "Audit Checklist Report "))
    ap_, al = substantive_lines(Path(a.after), drop_titles=("Audit Plan - ", "Audit Checklist Report "))
    bw, aw = words(bl), words(al)
    sm = difflib.SequenceMatcher(None, bw, aw, autojunk=False)
    ratio = sm.ratio()
    removed = sum(i2 - i1 for tag, i1, i2, j1, j2 in sm.get_opcodes() if tag in ("delete", "replace"))
    added = sum(j2 - j1 for tag, i1, i2, j1, j2 in sm.get_opcodes() if tag in ("insert", "replace"))
    # Claims are checked against the RAW text (browser decoration included) so
    # a defect that lives in the noise - about:blank, a fixed page counter - is
    # still seen; the similarity figure above deliberately excludes it.
    btext, atext = raw_text(Path(a.before)), raw_text(Path(a.after))

    out = []
    out.append(f"# Before / after — {Path(a.before).name}  vs  {Path(a.after).name}\n")
    out.append(f"| | before | after |\n|---|---|---|\n| pages | {bp} | {ap_} |\n| substantive lines | {len(bl)} | {len(al)} |\n| words | {len(bw)} | {len(aw)} |\n")
    out.append(f"Word-level similarity after removing timestamps, browser titles, page counters and generation stamps: **{ratio:.1%}**. "
               f"Words removed: **{removed}**, words added: **{added}**.\n")

    if a.claims:
        claims = json.loads(Path(a.claims).read_text(encoding="utf-8"))
        out.append("| Defect | Before | After |\n|---|---|---|")
        for c in claims:
            def norm(k):
                return re.sub(r"\s+", " ", k) if isinstance(k, str) else k

            def has(text, key):
                return key is not None and norm(key) in text
            c = {k: norm(v) if k != "label" else v for k, v in c.items()}
            b_ok = (has(btext, c.get("before_contains")) if c.get("before_contains") else True) and not (c.get("before_absent") and c["before_absent"] in btext)
            a_ok = (has(atext, c.get("after_contains")) if c.get("after_contains") else True) and not (c.get("after_absent") and c["after_absent"] in atext)
            out.append(f"| {c['label']} | {'present' if b_ok else 'not seen'} | {'corrected' if a_ok else '**NOT CORRECTED**'} |")
    text = "\n".join(out) + "\n"
    print(text)
    if a.out:
        Path(a.out).write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
